spring:
  application:
    name: comp
  jpa:
    hibernate:
      ddlAuto: update
      formatSql: true
    showSql: true
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  ai:
    openai:
      api-key: ${OPENAI_API}
      chat:
        options:
          model: gpt-3.5-turbo