name: Frontend Tasks

on:
  push: { branches: [main, frontend] }
  pull_request: { branches: [main, frontend] }

jobs:
  lint-markdown:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install markdownlint-cli
        run: npm install -g markdownlint-cli

      - name: Lint Markdown files
        run: markdownlint '**/*.md'

  eslint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install Dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    needs:
      - lint-markdown
      - eslint

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm run test

  build:
    needs: test

    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: armemius
          password: ${{ secrets.ARMEMIUS_DOCKERHUB_RW }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: armemius/companion-app-frontend:latest

  deploy:
    needs: test
    permissions:
      contents: write

    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install Dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
  
  sync-frontend:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          persist-credentials: false

      - name: Set up Git configuration
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Checkout frontend branch into 'frontend' directory
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          ref: frontend
          path: frontend

      - name: Copy frontend code to main/frontend
        run: |
          mkdir -p frontend
          cp -R frontend/* ./frontend/
          rm -rf ./frontend/.github

      - name: Commit changes
        run: |
          git add frontend
          git commit -m "Sync frontend code to main/frontend" || echo "No changes to commit"

      - name: Push changes to main branch
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
